name: Trigger auto deployment for backend-mercado-de-obra-docker

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/backend-mercado-de-obra-docker-AutoDeployTrigger-5624f84f-c976-4647-b72a-2a43e4a805de.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BACKENDMERCADODEOBRADOCKER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BACKENDMERCADODEOBRADOCKER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BACKENDMERCADODEOBRADOCKER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}apps/backend
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.BACKENDMERCADODEOBRADOCKER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BACKENDMERCADODEOBRADOCKER_REGISTRY_PASSWORD }}
          containerAppName: backend-mercado-de-obra-docker
          resourceGroup: mercado-de-obra
          imageToBuild: rodrigowx/backend-mercado-de-obra-docker:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


