name: Trigger auto deployment for container-chat-mercado-de-obra

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch para deploy"
        required: true
        default: "master"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERCHATMERCADODEOBRA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERCHATMERCADODEOBRA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERCHATMERCADODEOBRA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: apps/chat-service
          file: apps/chat-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chat-app:latest
          build-args: |
            DATABASE_URL_MONGO=${{ secrets.DATABASE_URL_MONGO }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}

      - name: Run Prisma DB Push for Mongo
        working-directory: apps/chat-service
        run: npx prisma db push
        env:
          DATABASE_URL_MONGO: ${{ secrets.DATABASE_URL_MONGO }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: container-chat-mercado-de-obra
          resourceGroup: mercado-de-obra
          registryUrl: docker.io
          registryUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          registryPassword: ${{ secrets.DOCKERHUB_PASSWORD }}
          imageToDeploy: ${{ secrets.DOCKERHUB_USERNAME }}/chat-app:latest
