name: Trigger auto deployment for container-backend-mercado

on:
  push:
    branches: 
      - master
    paths:
      - '**'
      - '.github/workflows/container-backend-mercado-AutoDeployTrigger-2a653f05-6944-4765-83c8-7c3b914c85aa.yml'
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write   # Necessário para solicitar o OIDC JWT Token
      contents: read    # Necessário se você usa token do GitHub para repositórios privados

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERBACKENDMERCADO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERBACKENDMERCADO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERBACKENDMERCADO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: apps/backend
          file: apps/backend/Dockerfile
          push: true
          tags: |
            rodrigowx/backend-app:latest
          build-args: |
            AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
            AZURE_STORAGE_ACCOUNT_NAME=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
            AZURE_STORAGE_ACCOUNT_KEY=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
            AZURE_STORAGE_CONTAINER_NAME=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
            AZURE_COMMUNICATION_EMAIL_CONNECTION_STRING=${{ secrets.AZURE_COMMUNICATION_EMAIL_CONNECTION_STRING }}
            AZURE_COMMUNICATION_EMAIL_SENDER=${{ secrets.AZURE_COMMUNICATION_EMAIL_SENDER }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: container-backend-mercado
          resourceGroup: mercado-de-obra
          registryUrl: docker.io
          registryUsername: ${{ secrets.CONTAINERBACKENDMERCADO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERBACKENDMERCADO_REGISTRY_PASSWORD }}
          imageToBuild: rodrigowx/backend-app:latest
