name: Build and deploy Node.js app to Azure Web App - backend-mercado-de-obra

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: npm install, build, and test
        run: |
          cd ./apps/backend
          npm install
          npm run build --if-present

      - name: Run Prisma seed script
        run: |
          cd ./apps/backend
          npm run prisma:seed

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FDCACB85F5764FA0A1CA8889771CA26B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D82A1DC52B094BF5B8B2BAF35E3D97E1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B8DFDB741F1F4809ABE822BB8B45AF02 }}

      - name: Set environment variables in Azure Web App
        run: |
          az webapp config appsettings set --name backend-mercado-de-obra --resource-group MeuResourceGroup --settings DATABASE_URL=${{ secrets.DATABASE_URL }} FRONTEND_URL=${{ secrets.FRONTEND_URL }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "backend-mercado-de-obra"
          slot-name: "Production"
          package: .
