name: Deploy Backend na Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }} # Postgres connection string
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      NODE_ENV: production
      PORT: 5000

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Instalar dependências
        run: |
          cd apps/backend
          npm install

      - name: Gerar Prisma Client e Aplicar Migrations
        run: |
          cd apps/backend
          npx prisma generate
          npx prisma migrate deploy

      - name: Rodar Seed no Banco de Dados
        run: |
          cd apps/backend
          npm run prisma:seed

      - name: Gerar build
        run: |
          cd apps/backend
          npx nest build

      - name: Upload artifact para deployment
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: apps/backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Baixar artifact da build
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: Login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EB4C6A6F4C874354A616BCCF2233959C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8A795A19DD504934A4471104571ECB30 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6292D88CCC9B4AB29FAC3884FEA94B3B }}

      - name: Deploy no Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "backend-mercado-de-obra"
          slot-name: "Production"
          package: apps/backend
