name: Deploy Chat Service

on:
  push:
    branches: [master]
    paths:
      - "apps/chat-service/**"
      - "prisma/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/chat-app

jobs:
  deploy-chat:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          driver: docker-container
          buildkitd-config-inline: |
            version = "0.1"
            [worker]
              oci.enabled = true
              network = "host"
              platforms = ["linux/amd64"]
              
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .  # ✅ Contexto na raiz
          file: apps/chat-service/Dockerfile
          push: true
          tags: user/chat-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          builder: ${{ steps.buildx.outputs.name }}

      - name: Verify Build
        run: |
          docker buildx version
          docker buildx inspect
          docker buildx du --verbose

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: "chat-mercado-de-obra"
          slot-name: "Production"
          images: "${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}"
