name: Deploy Frontend (Manual)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch para deploy"
        required: true
        default: "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Vercel CLI
        run: npm install -g vercel

      # ✅ Configurar projeto na Vercel
      - name: Configurar Projeto na Vercel
        run: vercel link --yes --token ${{ secrets.VERCEL_TOKEN }}

      # ✅ Definir as variáveis de ambiente no Vercel antes do deploy
      - name: Definir variáveis no Vercel
        run: |
          vercel env add NEXT_PUBLIC_GRAPHQL_URI ${{ secrets.NEXT_PUBLIC_GRAPHQL_URI }} --token ${{ secrets.VERCEL_TOKEN }}
          vercel env add NEXT_PUBLIC_CHAT_URI ${{ secrets.NEXT_PUBLIC_CHAT_URI }} --token ${{ secrets.VERCEL_TOKEN }}

      # 🚀 Deploy direto na Vercel
      - name: Deploy na Vercel
        run: vercel deploy --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
