name: Deploy Frontend (Manual)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch para deploy"
        required: true
        default: "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Vercel CLI
        run: npm install -g vercel

      - name: Configurar Projeto na Vercel
        run: vercel link --yes --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy na Vercel
        run: vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
